### ISSUE TITLE
Linking problems with v1.33.0 on amd64/linux

### ISSUE THREAD

**Issue by gsora** [herumi/bls-eth-go-binary#56]
Hi,
after upgrading from v1.32.1 to v1.33.0, building binaries with amd64/linux as target breaks at link time:

```
#21 84.18 /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
#21 84.18 /usr/bin/ld: /go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.33.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `Xbyak::LabelManager::LabelManager()':
#21 84.18 fp.cpp:(.text._ZN5Xbyak12LabelManagerC2Ev[_ZN5Xbyak12LabelManagerC2Ev]+0x311): undefined reference to `std::__throw_bad_array_new_length()'
#21 84.18 /usr/bin/ld: /go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.33.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `Xbyak::MmapAllocator::MmapAllocator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
#21 84.18 fp.cpp:(.text._ZN5Xbyak13MmapAllocatorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5Xbyak13MmapAllocatorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x184): undefined reference to `std::__throw_bad_array_new_length()'
#21 84.18 /usr/bin/ld: /go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.33.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `std::tr1::_Hashtable<unsigned long, std::pair<unsigned long const, Xbyak::MmapAllocator::Allocation>, std::allocator<std::pair<unsigned long const, Xbyak::MmapAllocator::Allocation> >, std::_Select1st<std::pair<unsigned long const, Xbyak::MmapAllocator::Allocation> >, std::equal_to<unsigned long>, std::tr1::hash<unsigned long>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_M_rehash(unsigned long)':
#21 84.18 fp.cpp:(.text._ZNSt3tr110_HashtableImSt4pairIKmN5Xbyak13MmapAllocator10AllocationEESaIS6_ESt10_Select1stIS6_ESt8equal_toImENS_4hashImEENS_8__detail18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyELb0ELb0ELb1EE9_M_rehashEm[_ZNSt3tr110_HashtableImSt4pairIKmN5Xbyak13MmapAllocator10AllocationEESaIS6_ESt10_Select1stIS6_ESt8equal_toImENS_4hashImEENS_8__detail18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyELb0ELb0ELb1EE9_M_rehashEm]+0xe3): undefined reference to `std::__throw_bad_array_new_length()'
#21 84.18 /usr/bin/ld: /go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.33.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `Xbyak::LabelManager::SlabelState::SlabelState()':
#21 84.18 fp.cpp:(.text._ZN5Xbyak12LabelManager11SlabelStateC2Ev[_ZN5Xbyak12LabelManager11SlabelStateC2Ev]+0x1fc): undefined reference to `std::__throw_bad_array_new_length()'
#21 84.18 /usr/bin/ld: /go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.33.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `std::tr1::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal> >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::tr1::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_Hashtable(std::tr1::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal> >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::tr1::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true> const&)':
#21 84.18 fp.cpp:(.text._ZNSt3tr110_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_N5Xbyak12LabelManager9SlabelValEESaISC_ESt10_Select1stISC_ESt8equal_toIS6_ENS_4hashIS6_EENS_8__detail18_Mod_range_hashingENSK_20_Default_ranged_hashENSK_20_Prime_rehash_policyELb0ELb0ELb1EEC2ERKSO_[_ZNSt3tr110_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_N5Xbyak12LabelManager9SlabelValEESaISC_ESt10_Select1stISC_ESt8equal_toIS6_ENS_4hashIS6_EENS_8__detail18_Mod_range_hashingENSK_20_Default_ranged_hashENSK_20_Prime_rehash_policyELb0ELb0ELb1EEC2ERKSO_]+0x194): undefined reference to `std::__throw_bad_array_new_length()'
#21 84.18 /usr/bin/ld: /go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.33.0/bls/lib/linux/amd64/libbls384_256.a(fp.o):fp.cpp:(.text._ZNSt3tr110_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_KN5Xbyak8JmpLabelEESaISC_ESt10_Select1stISC_ESt8equal_toIS6_ENS_4hashIS6_EENS_8__detail18_Mod_range_hashingENSK_20_Default_ranged_hashENSK_20_Prime_rehash_policyELb0ELb0ELb0EEC2ERKSO_[_ZNSt3tr110_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_KN5Xbyak8JmpLabelEESaISC_ESt10_Select1stISC_ESt8equal_toIS6_ENS_4hashIS6_EENS_8__detail18_Mod_range_hashingENSK_20_Default_ranged_hashENSK_20_Prime_rehash_policyELb0ELb0ELb0EEC2ERKSO_]+0x1a4): more undefined references to `std::__throw_bad_array_new_length()' follow
#21 84.18 collect2: error: ld returned 1 exit status
#21 84.18 
#21 ERROR: process "/bin/sh -c go build -o charon \"${GO_BUILD_FLAG}\" ." did not complete successfully: exit code: 1

#15 [linux/arm64 stage-1 2/8] RUN apt-get update && apt-get install -y ca-certificates wget
#15 CANCELED

#25 [linux/arm64 builder 6/7] RUN    --mount=type=cache,target=/go/pkg    --mount=type=cache,target=/root/.cache/go-build    go build -o charon "" .
#25 CANCELED
------
 > [linux/amd64 builder 6/7] RUN    --mount=type=cache,target=/go/pkg    --mount=type=cache,target=/root/.cache/go-build    go build -o charon "" .:
84.18 fp.cpp:(.text._ZN5Xbyak13MmapAllocatorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5Xbyak13MmapAllocatorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x184): undefined reference to `std::__throw_bad_array_new_length()'
84.18 /usr/bin/ld: /go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.33.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `std::tr1::_Hashtable<unsigned long, std::pair<unsigned long const, Xbyak::MmapAllocator::Allocation>, std::allocator<std::pair<unsigned long const, Xbyak::MmapAllocator::Allocation> >, std::_Select1st<std::pair<unsigned long const, Xbyak::MmapAllocator::Allocation> >, std::equal_to<unsigned long>, std::tr1::hash<unsigned long>, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_M_rehash(unsigned long)':
84.18 fp.cpp:(.text._ZNSt3tr110_HashtableImSt4pairIKmN5Xbyak13MmapAllocator10AllocationEESaIS6_ESt10_Select1stIS6_ESt8equal_toImENS_4hashImEENS_8__detail18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyELb0ELb0ELb1EE9_M_rehashEm[_ZNSt3tr110_HashtableImSt4pairIKmN5Xbyak13MmapAllocator10AllocationEESaIS6_ESt10_Select1stIS6_ESt8equal_toImENS_4hashImEENS_8__detail18_Mod_range_hashingENSE_20_Default_ranged_hashENSE_20_Prime_rehash_policyELb0ELb0ELb1EE9_M_rehashEm]+0xe3): undefined reference to `std::__throw_bad_array_new_length()'
84.18 /usr/bin/ld: /go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.33.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `Xbyak::LabelManager::SlabelState::SlabelState()':
84.18 fp.cpp:(.text._ZN5Xbyak12LabelManager11SlabelStateC2Ev[_ZN5Xbyak12LabelManager11SlabelStateC2Ev]+0x1fc): undefined reference to `std::__throw_bad_array_new_length()'
84.18 /usr/bin/ld: /go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.33.0/bls/lib/linux/amd64/libbls384_256.a(fp.o): in function `std::tr1::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal> >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::tr1::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_Hashtable(std::tr1::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Xbyak::LabelManager::SlabelVal> >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::tr1::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true> const&)':
84.18 fp.cpp:(.text._ZNSt3tr110_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_N5Xbyak12LabelManager9SlabelValEESaISC_ESt10_Select1stISC_ESt8equal_toIS6_ENS_4hashIS6_EENS_8__detail18_Mod_range_hashingENSK_20_Default_ranged_hashENSK_20_Prime_rehash_policyELb0ELb0ELb1EEC2ERKSO_[_ZNSt3tr110_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_N5Xbyak12LabelManager9SlabelValEESaISC_ESt10_Select1stISC_ESt8equal_toIS6_ENS_4hashIS6_EENS_8__detail18_Mod_range_hashingENSK_20_Default_ranged_hashENSK_20_Prime_rehash_policyELb0ELb0ELb1EEC2ERKSO_]+0x194): undefined reference to `std::__throw_bad_array_new_length()'
84.18 /usr/bin/ld: /go/pkg/mod/github.com/herumi/bls-eth-go-binary@v1.33.0/bls/lib/linux/amd64/libbls384_256.a(fp.o):fp.cpp:(.text._ZNSt3tr110_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_KN5Xbyak8JmpLabelEESaISC_ESt10_Select1stISC_ESt8equal_toIS6_ENS_4hashIS6_EENS_8__detail18_Mod_range_hashingENSK_20_Default_ranged_hashENSK_20_Prime_rehash_policyELb0ELb0ELb0EEC2ERKSO_[_ZNSt3tr110_HashtableINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS6_KN5Xbyak8JmpLabelEESaISC_ESt10_Select1stISC_ESt8equal_toIS6_ENS_4hashIS6_EENS_8__detail18_Mod_range_hashingENSK_20_Default_ranged_hashENSK_20_Prime_rehash_policyELb0ELb0ELb0EEC2ERKSO_]+0x1a4): more undefined references to `std::__throw_bad_array_new_length()' follow
84.18 collect2: error: ld returned 1 exit status
84.18 
```

You can reproduce this issue by cloning https://github.com/ObolNetwork/charon/ and compiling through docker:

```
docker -t obolnetwork/charon:local .
```

**Comment by mcdee** [comment]
Try updating your docker from bullseye to bookworm.

**Comment by herumi** [comment]
The problem happens when the compiled binary in a new environment is used in an old environment.
Could you mind updating your gcc and libc?

**Comment by herumi** [comment]
Alternatively, could you build a library yourself on your system?

**Comment by gsora** [comment]
Fixed by updating to debian Bookwork!
